config/routes.rb
Hydradam::Application.routes.draw do
  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  root :to => "catalog#index"

  resources :generic_files

  resources :generic_files do
    member do
      post 'audit'
    end
  end
  resources :assets do
    resources :subjects, :only=>[:new,:create]
    resources :pbcore, :only=>[:new,:create]
  end
  
  match "assets/:asset_id/subjects/:subject_type/:index" => "subjects#show", :as => :asset_subject, :via => :get

  match "assets/:asset_id/pbcore/:node/:index" => "pbcore#show", :as => :asset_pbcore, :via => :get

  match "assets/:asset_id/subjects/:subject_type/:index" => "subjects#destroy", :via => :delete

  match "assets/:asset_id/pbcore/:node/:index" => "pbcore#destroy", :via => :delete
  

  match "catalog/:id/solr" => "catalog#solr"

  devise_for :users

end

app/models/generic_file.rb
require "psu-customizations"

class GenericFile < ActiveFedora::Base
  include Hydra::ModelMixins::CommonMetadata
  include Hydra::ModelMethods

  has_metadata :name => "characterization", :type => FitsDatastream
  has_metadata :name => "descMetadata", :type => GenericFileRDFDatastream
  has_metadata :name => "Exiftool", :type => ExiftoolDatastream
  has_file_datastream :type => FileContentDatastream

  belongs_to :batch, :property => "isPartOf"

  delegate :related_url, :to => :descMetadata
  delegate :based_near, :to => :descMetadata
  delegate :part_of, :to => :descMetadata
  delegate :contributor, :to => :descMetadata
  delegate :creator, :to => :descMetadata
  delegate :title, :to => :descMetadata
  delegate :description, :to => :descMetadata
  delegate :publisher, :to => :descMetadata
  delegate :date_created, :to => :descMetadata
  delegate :date_uploaded, :to => :descMetadata
  delegate :date_modified, :to => :descMetadata
  delegate :subject, :to => :descMetadata
  delegate :language, :to => :descMetadata
  delegate :date, :to => :descMetadata
  delegate :rights, :to => :descMetadata
  delegate :resource_type, :to => :descMetadata
  delegate :format, :to => :descMetadata
  delegate :identifier, :to => :descMetadata

  delegate :format_label, :to => :characterization
  delegate :mime_type, :to => :characterization
  delegate :file_size, :to => :characterization
  delegate :last_modified, :to => :characterization
  delegate :filename, :to => :characterization
  delegate :original_checksum, :to => :characterization
  delegate :well_formed, :to => :characterization
  delegate :file_title, :to => :characterization
  delegate :file_author, :to => :characterization
  delegate :page_count, :to => :characterization


  ## From psu's gamma head -- we're doing this step out-of-band...
  # before_save :characterize

  ## Extract the metadata from the content datastream and record it in the characterization datastream
  def characterize
    if content.changed?
      characterization.content = content.extract_metadata
    end
  end
  
  
  def to_solr(solr_doc={})
    super(solr_doc)
    solr_doc["label_t"] = self.label
    return solr_doc
  end
  
  def label=(new_label)
    @inner_object.label = new_label
    if self.title.empty?
      title = new_label
    end
  end
  
end

app/controllers/generic_files_controller.rb
class GenericFilesController < ApplicationController
  
  include Hydra::Controller
  include Hydra::AssetsControllerHelper  # This is to get apply_depositor_metadata method
  include Hydra::FileAssetsHelper

  before_filter :authenticate_user!
  before_filter :enforce_access_controls, :only=>[:edit, :update]
  
  def new
    @generic_file = GenericFile.new 
    @dc_metadata = [['Title', 'title'], ['Creator', 'creator'], ['Publisher', 'publisher'], ['Description', 'description']]
  end

  def edit
    @generic_file = GenericFile.find(params[:id])
    @document_fedora = @generic_file
  end

  def create
    create_and_save_generic_files_from_params

    if @generic_files.empty? 
      flash[:notice] = "You must specify a file to upload" 
      redirect_params = {:controller => "generic_files", :action => "new"} 
    elsif params[:generic_file].has_key? :creator and params[:generic_file][:creator].empty?
      flash[:notice] = "You must include a creator."
      redirect_params = {:controller => "generic_files", :action => "new"} 
    else
      notice = []
      @generic_files.each do |gf|
        notice << render_to_string(:partial=>'generic_files/asset_saved_flash', :locals => { :generic_file => gf })
      end
      flash[:notice] = notice.join("<br/>").html_safe unless notice.blank?
      redirect_params = {:controller => "catalog", :action => "index"} 
    end
    redirect_to redirect_params 
  end

  def show
    @generic_file = GenericFile.find(params[:id])
  end

  def audit
    @generic_file = GenericFile.find(params[:id])
    render :json=>@generic_file.content.audit
  end
 
  def update
    @generic_file = GenericFile.find(params[:id])
    logger.debug("attributes submitted: #{sanitized_params.inspect}")
    update_document(@generic_file, sanitized_params)
    @generic_file.update_attributes((params[:generic_file] || {}).reject {|k,v| k=="Filedata" || k=="Filename"})
    flash[:notice] = "Successfully updated." 
    if params.has_key?(:Filedata) 
        add_posted_blob_to_asset(generic_file,params[:Filedata])
    end 
    @document_fedora = @generic_file
    render :edit 
  end


  protected
  def sanitized_params
    @sanitized_params ||= begin
      sanitize_update_params
                          end
  end
  # takes form file inputs and assigns meta data individually 
  # to each generic file asset and saves generic file assets # @param [Hash] of form fields
  def create_and_save_generic_files_from_params
    @generic_files = []
    if params.has_key?(:Filedata)
      params[:Filedata].each do |file|
        params[:generic_file] = {} unless params.has_key? :generic_file
        generic_file = GenericFile.new((params[:generic_file] || {}).reject {|k,v| k=="Filedata" || k=="Filename"})
        
        add_posted_blob_to_asset(generic_file,file)
        apply_depositor_metadata(generic_file)
        generic_file.label = file.original_filename
        # Delete this next line when GenericFile.label no longer wipes out the title
        generic_file.title = params[:generic_file][:title] if params[:generic_file].has_key?(:title) 
        generic_file.creator = params[:generic_file][:creator] if params[:generic_file].has_key?(:creator)
        generic_file.contributor = params[:generic_file][:contributor] if params[:generic_file].has_key?(:contributor)
        generic_file.publisher = params[:generic_file][:publisher] if params[:generic_file].has_key?(:publisher)
        generic_file.save
        
        f = GenericFile.find(generic_file.pid); f.owner_id = current_user.email; f.save
        @generic_files << f 
      end
    end
    @generic_files
  end

end

app/views/generic_files/_asset_saved_flash.html.erb
The file <%= link_to(generic_file.label, catalog_url(generic_file.pid)) %> has been saved.

app/views/generic_files/_assets.html.erb
<dl id="generic_content_metadata_view" class="type-metadata">
  <dt>View Content</dt>

  <%= render_media_partial @document %>

  <%= list_downloadables(@document_fedora.datastreams).html_safe %>
</dl>

app/views/generic_files/edit.html.erb
<h1>Edit <%= @generic_file.title %></h1>
<div class="viewing_context">
  <%= link_to "Browse view", generic_file_path %>
</div>
<%= form_for @generic_file do |f| %>
<h2>Upload File</h2>
<div class="uploader-contents">
  <p>Browse to upload a file.</p>
  <!-- <input name="Filedata-orig" type="file" /> -->
  <%= f.file_field "Filedata" %>
</div>


<h2 id="permissions" class="section-title">Set Permissions</h2>
  <div id="permissions_editor">
    <%= render :partial => "hydra/permissions/permissions_form", :locals => {:document => @generic_file, :asset_id=>params[:id]} %>
  </div>


<h2>Audit</h2>
Audit status:   <%= @generic_file.content.audit.pass  %>

<h2>Metadata</h2>
<%= f.label :contributor%> <%= f.text_field :contributor %> <br />
<%= f.label :creator%> <%= f.text_field :creator %> <br />
<%= f.label :title%> <%= f.text_field :title %> <br />
<%= f.submit "Save Changes" %>
<% end %>

app/views/generic_files/new.html.erb
<div class="page-header">
  <h1>Upload Files</h1>
  <p> When you have completed your upload you will automatically be redirected to the <%= link_to("dashboard", catalog_index_path) %>.</p>
</div>
<%= form_for(@generic_file, :html => {:multipart => true, :class => 'form-horizontal'}) do |f| %>
<%= hidden_field_tag(:file_count, "1") %>
<%= hidden_field_tag(:extra_description_count, "1") %>

<div class="uploader-contents">
  <div class="row">
    <div class="span3">
      <h2>Choose File(s)</h2>
    </div>
    <div class="span9">
      <p>Select a file to upload from your computer.  Click the <strong>Add Files</strong> button to upload more than one file.</p>
      <p id="upload_field_1">
      <%= file_field_tag "Filedata[]" %>
      </p>
      <div id="additional_files"></div>
      <%= f.submit :value => "+Add More Files", :name=> "additional_files_submit", :id => "additional_files_submit", :class=> "btn-info btn-small"  %>
    </div> <!-- close .span9 -->
  </div><!-- close .row choose file section-->

  <div class="row">
    <div class="span3">
        <h2>Description(s)</h2>
    </div>
    <div class="span9">
      <div class="control-group">
        <%= f.label :title, :class=>"control-label" %> <%= f.text_field :title, :class=>"controls" %>  
      </div>
      <div class="control-group">
        <%= f.label :creator, :class=>"control-label" %> <%= f.text_field :creator, :class=>"controls" %>
      </div>
      <div class="control-group">
        <%= f.label :contributor, :class=>"control-label" %> <%= f.text_field :contributor, :class=>"controls"  %> 
      </div>
      <div id="more_descriptions">
        <div class="control-group" id="extra_description_1">
          <%= select_tag(:metadata_key_1, options_for_select(([['More Descriptions', '0']] | @dc_metadata))) %>
          <%= text_field_tag(:metadata_value_1) %>
        </div><!-- close #extra_description_1 -->
      </div><!-- close #more_descriptions -->
      <div class="control-group">
        <%= f.submit :value => "+Add More Descriptions", :name=> "additional_md_submit", :id => "additional_md_submit", :class => "btn-info btn-small"  %>
      </div>
    </div> <!-- close .span9 -->
  </div><!-- close .row description section -->

<div class="form-actions">
  <%= f.submit :value => "Upload", :name => "upload_submit", :id => "upload_submit", :class => "btn-primary btn-large" %>
</div>
</div><!-- close .uploader-contents -->
<% end %>

app/views/generic_files/show.html.erb
<h1><%= @generic_file.title %></h1>
<div class="viewing_context">
  <%= link_to "Edit view", edit_generic_file_path %>
</div>
<dl>
  <dt>Title<dt><dd><%= @generic_file.title %></dd>
  <dt>Creator<dt><dd><%= @generic_file.creator %></dd>
  <dt>Contributor<dt><dd><%= @generic_file.contributor %></dd>
</dl>